import type { MainLunchMenu } from './types';

export const mockLunchMenus: MainLunchMenu[] = [
  {
    id: 1,
    cafeteriaName: '학생식당 A',
    mealTime: '점심',
    title: '불고기 덮밥',
    description: '맑은 장국, 김치, 샐러드와 함께 나오는 든든한 한 끼',
    detailDescription:
      '달짝지근한 불고기와 따끈한 밥이 어우러진 무난한 인기 메뉴예요. 점심시간에 부담 없이 먹기 좋고, 샐러드와 장국까지 같이 나와서 만족도가 높아요.',
    price: 5500,
    calorie: 742,
    sideMenus: ['맑은 장국', '배추김치', '샐러드'],
    location: '학생식당 A 1층',
    spicyLevel: '순한맛',
    likedCount: 82,
    dislikedCount: 7,
  },
  {
    id: 2,
    cafeteriaName: '학생식당 B',
    mealTime: '점심',
    title: '돈까스 정식',
    description: '바삭한 돈까스와 크림스프, 양배추 샐러드 구성',
    detailDescription:
      '겉은 바삭하고 속은 촉촉한 돈까스를 중심으로 구성된 정식 메뉴예요. 진한 크림스프와 샐러드 조합이 잘 어울려서 든든하게 먹기 좋아요.',
    price: 6000,
    calorie: 915,
    sideMenus: ['크림스프', '양배추 샐러드', '단무지'],
    location: '학생식당 B 2층',
    spicyLevel: '순한맛',
    likedCount: 74,
    dislikedCount: 12,
  },
  {
    id: 3,
    cafeteriaName: '교직원식당',
    mealTime: '점심',
    title: '닭갈비 볶음',
    description: '매콤한 닭갈비와 계란찜, 나물 반찬이 함께 제공',
    detailDescription:
      '불향이 은은하게 살아 있는 닭갈비 볶음 메뉴예요. 계란찜과 나물 반찬이 함께 제공돼서 매콤함을 중화해주고, 든든한 점심 메뉴로 인기가 많아요.',
    price: 6500,
    calorie: 688,
    sideMenus: ['계란찜', '콩나물무침', '무생채'],
    location: '교직원식당 1층',
    spicyLevel: '보통맛',
    likedCount: 96,
    dislikedCount: 9,
  },
  {
    id: 4,
    cafeteriaName: '학생식당 A',
    mealTime: '점심',
    title: '김치찌개 백반',
    description: '얼큰한 김치찌개와 공깃밥, 밑반찬 3종 구성',
    detailDescription:
      '푹 익은 김치와 돼지고기를 넣고 끓인 얼큰한 김치찌개예요. 뜨끈한 국물이 든든해서 날씨가 쌀쌀할 때 특히 인기가 많아요.',
    price: 5000,
    calorie: 654,
    sideMenus: ['공깃밥', '멸치볶음', '어묵볶음'],
    location: '학생식당 A 1층',
    spicyLevel: '매운맛',
    likedCount: 88,
    dislikedCount: 5,
  },
  {
    id: 5,
    cafeteriaName: '학생식당 B',
    mealTime: '점심',
    title: '제육볶음 정식',
    description: '매콤달콤한 제육볶음과 쌈채소, 된장국 구성',
    detailDescription:
      '불맛 가득한 제육볶음을 쌈채소에 싸 먹는 정식 메뉴예요. 된장국과 함께 나와서 자극적이지 않게 마무리할 수 있어요.',
    price: 6000,
    calorie: 780,
    sideMenus: ['쌈채소', '된장국', '콩자반'],
    location: '학생식당 B 2층',
    spicyLevel: '매운맛',
    likedCount: 101,
    dislikedCount: 11,
  },
  {
    id: 6,
    cafeteriaName: '교직원식당',
    mealTime: '점심',
    title: '순두부찌개',
    description: '얼큰한 순두부찌개와 계란후라이, 공깃밥 구성',
    detailDescription:
      '부드러운 순두부와 해물이 어우러진 얼큰한 찌개예요. 계란후라이를 올려 먹으면 더 고소하게 즐길 수 있어요.',
    price: 5500,
    calorie: 598,
    sideMenus: ['공깃밥', '계란후라이', '깍두기'],
    location: '교직원식당 1층',
    spicyLevel: '보통맛',
    likedCount: 79,
    dislikedCount: 8,
  },
  {
    id: 7,
    cafeteriaName: '학생식당 A',
    mealTime: '점심',
    title: '비빔밥',
    description: '나물 5종과 고추장, 계란후라이가 올라간 비빔밥',
    detailDescription:
      '신선한 나물 여러 가지를 넉넉하게 넣고 고추장에 비벼 먹는 메뉴예요. 채식 위주로 가볍게 먹고 싶을 때 추천해요.',
    price: 5500,
    calorie: 612,
    sideMenus: ['계란후라이', '고추장', '미역국'],
    location: '학생식당 A 1층',
    spicyLevel: '순한맛',
    likedCount: 91,
    dislikedCount: 6,
  },
  {
    id: 8,
    cafeteriaName: '학생식당 B',
    mealTime: '점심',
    title: '카레라이스',
    description: '부드러운 카레와 감자, 당근, 돈육이 들어간 한 그릇',
    detailDescription:
      '진한 카레 소스에 감자와 당근, 돼지고기가 듬뿍 들어간 메뉴예요. 순한 맛이라 매운 음식이 부담스러운 날 먹기 좋아요.',
    price: 5000,
    calorie: 705,
    sideMenus: ['단무지', '피클', '요구르트'],
    location: '학생식당 B 2층',
    spicyLevel: '순한맛',
    likedCount: 85,
    dislikedCount: 4,
  },
  {
    id: 9,
    cafeteriaName: '기숙사식당',
    mealTime: '점심',
    title: '짜장밥',
    description: '달콤짭짤한 짜장 소스와 채소가 올라간 덮밥',
    detailDescription:
      '춘장을 볶아 만든 진한 짜장 소스를 밥에 올린 덮밥 메뉴예요. 자취생·기숙사생들에게 익숙한 인기 메뉴예요.',
    price: 5000,
    calorie: 733,
    sideMenus: ['단무지', '군만두 1개', '오이무침'],
    location: '기숙사식당 지하 1층',
    spicyLevel: '순한맛',
    likedCount: 77,
    dislikedCount: 9,
  },
  {
    id: 10,
    cafeteriaName: '기숙사식당',
    mealTime: '점심',
    title: '오므라이스',
    description: '폭신한 계란 지단과 케첩 소스를 얹은 볶음밥',
    detailDescription:
      '채소와 햄을 넣고 볶은 밥 위에 폭신한 계란 지단을 올린 메뉴예요. 케첩 소스와 함께 부드럽게 즐길 수 있어요.',
    price: 5500,
    calorie: 689,
    sideMenus: ['피클', '양상추 샐러드'],
    location: '기숙사식당 지하 1층',
    spicyLevel: '순한맛',
    likedCount: 83,
    dislikedCount: 5,
  },
  {
    id: 11,
    cafeteriaName: '학생식당 A',
    mealTime: '점심',
    title: '규동',
    description: '얇게 썬 소고기와 양파를 달짝지근하게 조린 일본식 덮밥',
    detailDescription:
      '간장 베이스 소스에 소고기와 양파를 조려 밥 위에 올린 일본식 덮밥이에요. 짭짤달콤한 맛이 자극적이지 않아 부담없이 즐길 수 있어요.',
    price: 6500,
    calorie: 745,
    sideMenus: ['미소국', '단무지'],
    location: '학생식당 A 1층',
    spicyLevel: '순한맛',
    likedCount: 94,
    dislikedCount: 6,
  },
  {
    id: 12,
    cafeteriaName: '학생식당 B',
    mealTime: '점심',
    title: '잡채밥',
    description: '당면과 채소가 듬뿍 들어간 잡채와 공깃밥 구성',
    detailDescription:
      '쫄깃한 당면과 다양한 채소, 소고기를 볶아 만든 잡채를 밥과 함께 먹는 메뉴예요. 달콤짭짤한 맛이 남녀노소 인기가 많아요.',
    price: 6000,
    calorie: 710,
    sideMenus: ['공깃밥', '배추김치', '계란국'],
    location: '학생식당 B 2층',
    spicyLevel: '순한맛',
    likedCount: 87,
    dislikedCount: 7,
  },
  {
    id: 13,
    cafeteriaName: '교직원식당',
    mealTime: '점심',
    title: '된장찌개 백반',
    description: '구수한 된장찌개와 제철 나물 반찬 3종',
    detailDescription:
      '구수하고 담백한 된장찌개에 두부와 애호박을 넉넉히 넣었어요. 나물 반찬과 함께 담백한 한 끼를 원할 때 추천해요.',
    price: 5500,
    calorie: 560,
    sideMenus: ['공깃밥', '고사리나물', '시금치나물'],
    location: '교직원식당 1층',
    spicyLevel: '순한맛',
    likedCount: 72,
    dislikedCount: 4,
  },
  {
    id: 14,
    cafeteriaName: '학생식당 A',
    mealTime: '점심',
    title: '치킨마요 덮밥',
    description: '바삭한 치킨과 마요소스가 어우러진 인기 덮밥',
    detailDescription:
      '튀긴 치킨에 달콤짭짤한 마요 소스를 뿌린 덮밥 메뉴예요. 학생들 사이에서 꾸준히 인기가 많은 메뉴 중 하나예요.',
    price: 6000,
    calorie: 820,
    sideMenus: ['미소국', '단무지', '양배추 샐러드'],
    location: '학생식당 A 1층',
    spicyLevel: '순한맛',
    likedCount: 118,
    dislikedCount: 10,
  },
  {
    id: 15,
    cafeteriaName: '교직원식당',
    mealTime: '점심',
    title: '떡갈비 정식',
    description: '부드러운 떡갈비와 쌈채소, 된장찌개 구성',
    detailDescription:
      '다진 소고기와 돼지고기를 섞어 만든 떡갈비를 노릇하게 구워낸 메뉴예요. 쌈채소와 함께 먹으면 더 든든해요.',
    price: 7000,
    calorie: 860,
    sideMenus: ['쌈채소', '된장찌개', '깍두기'],
    location: '교직원식당 1층',
    spicyLevel: '순한맛',
    likedCount: 99,
    dislikedCount: 8,
  },
  {
    id: 16,
    cafeteriaName: '학생식당 B',
    mealTime: '점심',
    title: '고등어구이 정식',
    description: '노릇하게 구운 고등어와 무생채, 된장국 구성',
    detailDescription:
      '기름이 오른 고등어를 노릇하게 구워낸 든든한 정식이에요. 무생채와 함께 먹으면 비린내 없이 깔끔하게 즐길 수 있어요.',
    price: 6500,
    calorie: 690,
    sideMenus: ['공깃밥', '무생채', '된장국'],
    location: '학생식당 B 2층',
    spicyLevel: '보통맛',
    likedCount: 68,
    dislikedCount: 6,
  },
  {
    id: 17,
    cafeteriaName: '기숙사식당',
    mealTime: '점심',
    title: '크림 파스타',
    description: '베이컨과 버섯이 들어간 진한 크림 파스타',
    detailDescription:
      '고소하고 진한 크림 소스에 베이컨과 버섯을 넣어 볶은 파스타예요. 느끼한 걸 좋아하는 분들에게 인기가 많아요.',
    price: 6500,
    calorie: 812,
    sideMenus: ['마늘빵', '피클'],
    location: '기숙사식당 지하 1층',
    spicyLevel: '순한맛',
    likedCount: 76,
    dislikedCount: 13,
  },
  {
    id: 18,
    cafeteriaName: '학생식당 A',
    mealTime: '점심',
    title: '부대찌개',
    description: '햄, 소시지, 라면사리가 들어간 얼큰한 부대찌개',
    detailDescription:
      '햄과 소시지, 라면사리까지 푸짐하게 들어간 얼큰한 찌개예요. 여럿이 나눠 먹기 좋아서 함께 식사할 때 인기가 많아요.',
    price: 7000,
    calorie: 890,
    sideMenus: ['공깃밥', '라면사리', '배추김치'],
    location: '학생식당 A 1층',
    spicyLevel: '매운맛',
    likedCount: 105,
    dislikedCount: 9,
  },
];
